all : compile run

compile:
	g++ -std=c++14 Date.cpp Gender.cpp Exceptions.cpp Disability.cpp BookingClasses.cpp Station.cpp Passenger.cpp BookingCategory.cpp Railways.cpp Booking.cpp UnitTesting.cpp 

run:
	./a.out