all : compile run

compile:
	g++ -std=c++11 Passenger.cpp  Railways.cpp Booking.cpp BookingClasses.cpp Date.cpp Station.cpp ApplicationTesting.cpp 

run:
	./a.out 
	g++ -std=c++11 Passenger.cpp  Railways.cpp Booking.cpp BookingClasses.cpp Date.cpp Station.cpp UnitTesting.cpp 
	./a.out